name: AutoRebase

on:
  workflow_dispatch:

jobs:
  AUTO-REBASE:
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: AutoRebase
      env:
        # GITHUB_TOKEN is used for this repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # BOT_GITHUB_TOKEN is used for other BladeDISC repo
        BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      run: bash scripts/ci/auto_rebase.sh
